### ISSUE TITLE
ESSID Filtering

### ISSUE THREAD

**Issue by beetlebone** [smythtech/WifiProbeMapper#2]
Been looking for something like this for a long time.
Love your code, However my coding skills are a bit lacking.
We have a lot of WifiSpots around here is there a way to pass some sort of essid filtering?
Tnx

**Comment by smythtech** [comment]
I've just added a whitelist and blacklist option to the config.js file. This should be an array of ssid strings you want to allow or ignore.

I've only tested this a little bit so let me know if you have any issues.

**Comment by smythtech** [comment]
I'm going to guess everything is ok so I'll close this issue.
